/**
 * Interactive white-label clone wizard.
 */
import {
  PLATFORM_ROOT,
  ask,
  askYesNo,
  c,
  classifyPath,
  copyFile,
  createRl,
  defaultCloneDir,
  git,
  isCloneExcluded,
  isHexColor,
  loadBrandConfig,
  loadPathsManifest,
  slugify,
  walkFiles,
  writeJson,
} from "./shared.mjs";
import { execSync } from "node:child_process";
import path from "node:path";
import fs from "node:fs";

function renderBrandTs(brand) {
  const rewardPrefix = `${brand.name.replace(/[^A-Za-z0-9]/g, "").toUpperCase()}-`;
  return `/**
 * Brand identity for this deploy.
 *
 * Generated by \`npm run brand:clone\`. Keep colors in sync with
 * \`tailwind.config.ts\` → \`cat4.*\` tokens (class names stay \`cat4-*\` so
 * platform syncs stay mergeable — see \`.brand/README.md\`).
 */
export const brand = {
  /** Short machine id — used in storage key prefixes. Keep stable per deploy. */
  id: ${JSON.stringify(brand.id)},
  /** Display name in chrome, metadata, and default copy. */
  name: ${JSON.stringify(brand.name)},
  /** Optional longer legal / entity name (consent, footer). Defaults to \`name\`. */
  legalName: ${JSON.stringify(brand.legalName)},
  /** Canonical public site URL (no trailing slash). Keep in sync with Vercel AUTH_URL. */
  url: ${JSON.stringify(brand.url)},
  tagline: ${JSON.stringify(brand.tagline)},
  description:
    ${JSON.stringify(brand.description)},
  /** Minimum age for the public age gate. */
  ageGateMinYears: ${brand.ageGateMinYears},
  colors: {
    /** Primary accent — keep in sync with \`tailwind.config.ts\` → \`cat4.blue\` / \`primary\`. */
    primary: ${JSON.stringify(brand.colors.primary)},
    dark: ${JSON.stringify(brand.colors.dark)},
    light: ${JSON.stringify(brand.colors.light)},
    surface: ${JSON.stringify(brand.colors.surface)},
  },
  defaults: {
    seedAdminEmail: ${JSON.stringify(brand.defaults.seedAdminEmail)},
    seedAdminName: ${JSON.stringify(brand.defaults.seedAdminName)},
    marketingConsent: ${JSON.stringify(brand.defaults.marketingConsent)},
    promotionConsent: ${JSON.stringify(brand.defaults.promotionConsent)},
    rewardCodePrefix: ${JSON.stringify(rewardPrefix)},
    hubTitle: ${JSON.stringify(brand.name)},
    hubLinkLabel: ${JSON.stringify(`Visit ${brand.name}`)},
  },
} as const;

export type Brand = typeof brand;

/** Cookie / localStorage / BroadcastChannel keys — namespaced by \`brand.id\`. */
export const brandStorageKeys = {
  ageVerified: \`\${brand.id}-age-verified\`,
  analyticsSession: \`\${brand.id}_analytics_session\`,
  homepagePreviewPopout: \`\${brand.id}-homepage-preview-popout\`,
  homepagePreviewChannel: \`\${brand.id}-homepage-preview\`,
} as const;

export function brandMetadataTitle(pageTitle?: string): string {
  if (!pageTitle) return \`\${brand.name} — \${brand.tagline}\`;
  return \`\${pageTitle} | \${brand.name}\`;
}
`;
}

function patchTailwindColors(content, colors) {
  return content
    .replace(/blue:\s*"[^"]+"/g, `blue: "${colors.primary}"`)
    .replace(/dark:\s*"[^"]+"/g, `dark: "${colors.dark}"`)
    .replace(/light:\s*"[^"]+"/g, `light: "${colors.light}"`)
    .replace(/surface:\s*"[^"]+"/g, `surface: "${colors.surface}"`)
    .replace(
      /primary:\s*\{\s*DEFAULT:\s*"[^"]+"/m,
      `primary: {\n          DEFAULT: "${colors.primary}"`
    )
    .replace(
      /accent:\s*\{\s*DEFAULT:\s*"[^"]+"/m,
      `accent: {\n          DEFAULT: "${colors.primary}"`
    )
    .replace(/ring:\s*"[^"]+"/g, `ring: "${colors.primary}"`);
}

function softReplaceBrandCopy(text, fromName, toName, fromId, toId) {
  // Conservative replacements for seed/copy files — not for Tailwind class names.
  let out = text;
  if (fromName && toName && fromName !== toName) {
    out = out.split(fromName).join(toName);
  }
  // Only replace id when it appears as a standalone word / email / storage style token,
  // not inside `cat4-blue` class names.
  if (fromId && toId && fromId !== toId) {
    const patterns = [
      new RegExp(`\\b${fromId}\\b(?!-)`, "g"), // word boundary, not followed by -
      new RegExp(`@${fromId}\\.`, "g"),
    ];
    for (const re of patterns) {
      out = out.replace(re, (m) => (m.startsWith("@") ? `@${toId}.` : toId));
    }
  }
  return out;
}

const EMPTY_PRODUCTS_SEED = `import type { Product } from "@/lib/db/schema";

/**
 * Product catalog for this brand deploy.
 * Starts empty after \`npm run brand:clone\` — add products in Admin → Products
 * (or replace this file / import your own catalog).
 */
export const MOCK_PRODUCTS: Product[] = [];
`;

const PLACEHOLDER_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800" viewBox="0 0 800 800" role="img" aria-label="Product placeholder">
  <rect width="800" height="800" fill="#231c2e"/>
  <rect x="80" y="80" width="640" height="640" rx="24" fill="#1A1423" stroke="#3d3548" stroke-width="2"/>
  <text x="400" y="390" text-anchor="middle" fill="#a1a1aa" font-family="system-ui,sans-serif" font-size="28">Add product images</text>
  <text x="400" y="430" text-anchor="middle" fill="#71717a" font-family="system-ui,sans-serif" font-size="18">Admin → Products</text>
</svg>
`;

/**
 * Strip source-brand catalog so the clone is ready for new products.
 * - empty mock products seed
 * - empty data/ + public/products/
 * - homepage defaults no longer point at source product images
 * - stub product-import script
 */
function stripCatalogForClone(destRoot, brandName) {
  fs.writeFileSync(path.join(destRoot, "src/lib/mock/products-seed.ts"), EMPTY_PRODUCTS_SEED);

  const dataDir = path.join(destRoot, "data");
  fs.mkdirSync(dataDir, { recursive: true });
  fs.writeFileSync(
    path.join(dataDir, "README.md"),
    `# Catalog data\n\nThis clone starts with an empty product catalog.\n\nAdd products in **Admin → Products**, or drop import files here and wire a brand-specific importer under \`scripts/\`.\n`
  );

  const productsDir = path.join(destRoot, "public/products");
  fs.mkdirSync(productsDir, { recursive: true });
  fs.writeFileSync(path.join(productsDir, ".gitkeep"), "");

  const brandPublic = path.join(destRoot, "public/brand");
  fs.mkdirSync(brandPublic, { recursive: true });
  const placeholderRel = "/brand/product-placeholder.svg";
  fs.writeFileSync(path.join(brandPublic, "product-placeholder.svg"), PLACEHOLDER_SVG);

  const homepagePath = path.join(destRoot, "src/lib/homepage.ts");
  if (fs.existsSync(homepagePath)) {
    let homepage = fs.readFileSync(homepagePath, "utf8");
    homepage = homepage.replace(
      /imageUrl:\s*"\/products\/[^"]*"/g,
      `imageUrl: "${placeholderRel}"`
    );
    fs.writeFileSync(homepagePath, homepage);
  }

  const importStub = path.join(destRoot, "scripts/import-products.mjs");
  fs.writeFileSync(
    importStub,
    `#!/usr/bin/env node
/**
 * Placeholder — ${brandName} product import.
 *
 * This clone intentionally ships with an empty catalog.
 * Add products via Admin → Products, or replace this script with a brand importer.
 */
console.log("${brandName}: no product importer yet. Add products in Admin → Products.");
process.exit(0);
`
  );

  const pkgPath = path.join(destRoot, "package.json");
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    if (pkg.scripts?.["import:products"]) {
      pkg.scripts["import:products"] = "node scripts/import-products.mjs";
      fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    }
  }
}


function writeChecklist(destRoot, brand) {
  const body = `# ${brand.name} clone checklist

Generated by \`npm run brand:clone\`.

## Done by the wizard
- [x] Copied platform into \`${destRoot}\`
- [x] Wrote \`src/lib/brand.ts\`
- [x] Updated Tailwind hex tokens (kept \`cat4-*\` class names for sync)
- [x] Updated \`package.json\` name → \`${brand.id}\`
- [x] Wrote \`.brand/lineage.json\`
- [x] Created \`.env.local\` from \`.env.example\` (mock mode)
- [x] Ran \`npm install\` (unless \`--skip-install\`)
- [x] Cleared product catalog (empty \`MOCK_PRODUCTS\`, no \`data/\` or \`public/products\` assets)

## Your next steps
- [ ] Replace logos / favicon / \`public/\` media
- [ ] **Add products** via Admin → Products (catalog starts empty)
- [ ] Rewrite homepage defaults in \`src/lib/homepage.ts\` (placeholders until products exist)
- [ ] Fill real AUTH_SECRET / Neon / Blob in \`.env.local\` when leaving mock mode
- [ ] Fresh Neon database + Vercel project
- [ ] \`npm run db:push && npm run db:seed\` (when using a real DB — seed inserts whatever is in \`MOCK_PRODUCTS\`)
- [ ] \`npm run brand:doctor\` and clear leftover "${brand.sourceName || "CAT4"}" strings
- [ ] Point git \`origin\` at this brand's remote ( \`platform\` already points upstream)

## Keeping in sync
\`\`\`bash
# From this clone — pull platform updates
npm run brand:sync -- pull --from ${JSON.stringify(brand.sourcePath)}

# Preview only
npm run brand:sync -- pull --from ${JSON.stringify(brand.sourcePath)} --dry-run

# Port a clone feature back into the platform
npm run brand:sync -- push --to ${JSON.stringify(brand.sourcePath)}
\`\`\`

See \`.brand/README.md\` for the full workflow.
`;
  fs.writeFileSync(path.join(destRoot, ".brand/CLONE_CHECKLIST.md"), body);
}

export async function runClone(argv = []) {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`Usage: npm run brand:clone [-- --name <n> --id <slug> --dir <path> --url <url> --yes --skip-install]`);
    console.log(`Default target: ${defaultCloneDir("<id>")}  (see .brand/config.json → clonesRoot)`);
    return;
  }

  const nonInteractive = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--name") nonInteractive.name = argv[++i];
    else if (a === "--id") nonInteractive.id = argv[++i];
    else if (a === "--dir") nonInteractive.dir = argv[++i];
    else if (a === "--url") nonInteractive.url = argv[++i];
    else if (a === "--yes") nonInteractive.yes = true;
    else if (a === "--skip-install") nonInteractive.skipInstall = true;
  }

  const rl = createRl();
  const sourceLineage = loadPathsManifest(PLATFORM_ROOT);
  const brandConfig = loadBrandConfig(PLATFORM_ROOT);
  const { clonesRoot, cloneExclude = [] } = brandConfig;
  const sourceBrandName = "CAT4";
  const sourceBrandId = "cat4";

  console.log(`\n${c("Brand clone wizard", "bold")}`);
  console.log(c(`Source: ${PLATFORM_ROOT}`, "dim"));
  console.log(c(`Clones root: ${clonesRoot}/<brand-id>`, "dim"));
  console.log(c("Creates a ready-to-run brand directory (empty product catalog).\n", "dim"));

  try {
    const name =
      nonInteractive.name ||
      (await ask(rl, "Brand display name", "Acme"));
    const id =
      nonInteractive.id ||
      (await ask(rl, "Brand id (slug, storage keys, package name)", slugify(name)));
    if (!/^[a-z][a-z0-9-]{1,47}$/.test(id)) {
      throw new Error("Brand id must be lowercase letters/numbers/hyphens, start with a letter.");
    }

    const legalName =
      nonInteractive.legalName ||
      (nonInteractive.yes ? name : await ask(rl, "Legal / entity name", name));
    const url =
      nonInteractive.url ||
      (nonInteractive.yes
        ? `https://${id}.example.com`
        : await ask(rl, "Public site URL", `https://${id}.example.com`));
    const tagline = nonInteractive.yes
      ? `${name}`
      : await ask(rl, "Tagline", "Your brand tagline");
    const description = nonInteractive.yes
      ? `${name} — ${tagline}`
      : await ask(rl, "Meta description", `${name} — ${tagline}`);

    const defaultDir = defaultCloneDir(id);
    const destRoot = path.resolve(
      nonInteractive.dir ||
        (nonInteractive.yes ? defaultDir : await ask(rl, "Target directory", defaultDir))
    );

    const colors = nonInteractive.yes
      ? { primary: "#2252d4", dark: "#1A1423", light: "#fdfdfd", surface: "#231c2e" }
      : await (async () => {
          console.log(c("\nColors (press Enter to keep platform defaults for now)", "dim"));
          return {
            primary: await ask(rl, "Primary", "#2252d4"),
            dark: await ask(rl, "Dark", "#1A1423"),
            light: await ask(rl, "Light", "#fdfdfd"),
            surface: await ask(rl, "Surface", "#231c2e"),
          };
        })();
    for (const [k, v] of Object.entries(colors)) {
      if (!isHexColor(v)) throw new Error(`Invalid hex for ${k}: ${v}`);
    }

    const emailDomain = (() => {
      try {
        return new URL(url).hostname.replace(/^www\./, "");
      } catch {
        return `${id}.com`;
      }
    })();

    const brand = {
      id,
      name,
      legalName,
      url: url.replace(/\/$/, ""),
      tagline,
      description,
      ageGateMinYears: 21,
      colors,
      defaults: {
        seedAdminEmail: `admin@${emailDomain}`,
        seedAdminName: `${name} Admin`,
        marketingConsent: `I agree to receive marketing emails from ${name}. Unsubscribe anytime.`,
        promotionConsent: `I agree to the official rules and to receive emails from ${name}.`,
      },
      sourceName: sourceBrandName,
      sourcePath: PLATFORM_ROOT,
    };

    if (fs.existsSync(destRoot) && fs.readdirSync(destRoot).length > 0) {
      const ok =
        nonInteractive.yes ||
        (await askYesNo(rl, `Target ${destRoot} is not empty. Continue anyway?`, false));
      if (!ok) {
        console.log("Aborted.");
        return;
      }
    }

    const initGit =
      nonInteractive.yes || (await askYesNo(rl, "Initialize a new git repo in the clone?", true));
    const addUpstream =
      initGit &&
      (nonInteractive.yes ||
        (await askYesNo(rl, "Add `platform` git remote pointing at this repo?", true)));

    console.log(`\n${c("Cloning…", "cyan")}`);
    fs.mkdirSync(path.dirname(destRoot), { recursive: true });
    fs.mkdirSync(destRoot, { recursive: true });

    const manifest = sourceLineage;
    const files = walkFiles(PLATFORM_ROOT);
    let copied = 0;
    let skipped = 0;

    for (const { abs, rel } of files) {
      const kind = classifyPath(rel, manifest);
      if (kind === "never") {
        skipped++;
        continue;
      }
      if (isCloneExcluded(rel, cloneExclude)) {
        skipped++;
        continue;
      }
      // Skip existing lineage/checklist; we rewrite them
      if (rel === ".brand/lineage.json" || rel === ".brand/CLONE_CHECKLIST.md") {
        skipped++;
        continue;
      }
      copyFile(abs, path.join(destRoot, rel));
      copied++;
    }

    // Rewrite brand skin
    fs.writeFileSync(path.join(destRoot, "src/lib/brand.ts"), renderBrandTs(brand));

    // Empty catalog — ready for Admin → Products (or a brand importer)
    stripCatalogForClone(destRoot, name);

    const twPath = path.join(destRoot, "tailwind.config.ts");
    if (fs.existsSync(twPath)) {
      fs.writeFileSync(twPath, patchTailwindColors(fs.readFileSync(twPath, "utf8"), colors));
    }

    const pkgPath = path.join(destRoot, "package.json");
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      pkg.name = id;
      fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    }

    const envExample = path.join(destRoot, ".env.example");
    if (fs.existsSync(envExample)) {
      let env = fs.readFileSync(envExample, "utf8");
      env = env
        .replace(/admin@cat4\.com/g, brand.defaults.seedAdminEmail)
        .replace(/https:\/\/cat4\.thcmoc\.com/g, brand.url);
      fs.writeFileSync(envExample, env);

      const envLocal = path.join(destRoot, ".env.local");
      if (!fs.existsSync(envLocal)) {
        fs.writeFileSync(envLocal, env);
      }
    }

    // Soft-replace CAT4 copy in skin text files only
    const skinTextExt = new Set([".ts", ".tsx", ".mjs", ".md", ".json", ".css", ".example"]);
    for (const { abs, rel } of walkFiles(destRoot)) {
      if (classifyPath(rel, manifest) !== "skin") continue;
      if (rel === "src/lib/brand.ts" || rel === "tailwind.config.ts") continue;
      if (rel === "src/lib/mock/products-seed.ts") continue;
      const ext = path.extname(rel);
      if (!skinTextExt.has(ext) && !rel.endsWith(".env.example")) continue;
      const before = fs.readFileSync(abs, "utf8");
      const after = softReplaceBrandCopy(before, sourceBrandName, name, sourceBrandId, id);
      if (after !== before) fs.writeFileSync(abs, after);
    }

    const sourceCommit = git("rev-parse HEAD", PLATFORM_ROOT, { optional: true });
    const sourceRemote = git("remote get-url origin", PLATFORM_ROOT, { optional: true });

    writeJson(path.join(destRoot, ".brand/lineage.json"), {
      schemaVersion: 1,
      role: "clone",
      brandId: id,
      brandName: name,
      packageName: id,
      createdAt: new Date().toISOString(),
      clonedFrom: {
        path: PLATFORM_ROOT,
        remote: sourceRemote,
        commit: sourceCommit,
        brandId: sourceBrandId,
        brandName: sourceBrandName,
      },
      upstreamRemote: "platform",
      notes: "Use npm run brand:sync to pull/push platform paths. Skin paths stay local.",
    });

    writeChecklist(destRoot, brand);

    if (initGit) {
      if (!fs.existsSync(path.join(destRoot, ".git"))) {
        git("init", destRoot);
      }
      if (addUpstream && sourceRemote) {
        const existing = git("remote", destRoot, { optional: true }) || "";
        if (existing.split("\n").includes("platform")) {
          git("remote set-url platform " + sourceRemote, destRoot);
        } else {
          git(`remote add platform ${sourceRemote}`, destRoot);
        }
      } else if (addUpstream) {
        const existing = git("remote", destRoot, { optional: true }) || "";
        if (existing.split("\n").includes("platform")) {
          git("remote set-url platform " + PLATFORM_ROOT, destRoot);
        } else {
          git(`remote add platform ${PLATFORM_ROOT}`, destRoot);
        }
      }
      git("add -A", destRoot);
      git(`commit -m "chore: clone platform as ${name} (${id})"`, destRoot, { optional: true });
    }

    const shouldInstall =
      !nonInteractive.skipInstall &&
      (nonInteractive.yes ||
        (await askYesNo(rl, "Run npm install so the clone is ready to go?", true)));
    if (shouldInstall) {
      console.log(c("\nInstalling dependencies…", "cyan"));
      try {
        execSync("npm install", { cwd: destRoot, stdio: "inherit" });
      } catch {
        console.log(c("npm install failed — run it manually in the clone.", "yellow"));
      }
    }

    console.log(`\n${c("Clone ready", "green")}`);
    console.log(`  Files copied: ${copied} (skipped never/env: ${skipped})`);
    console.log(`  Target:      ${destRoot}`);
    console.log(`  Checklist:    ${path.join(destRoot, ".brand/CLONE_CHECKLIST.md")}`);
    console.log(`\nNext:`);
    console.log(`  cd ${destRoot}`);
    console.log(`  npm run brand:doctor && npm run dev`);
  } finally {
    rl.close();
  }
}
